name: gpt2_small

_target_: src.model.GPTConfig

# These will be overridden by the data config
vocab_size: ${data.vocab_size}
block_size: ${data.block_size}

# GPT-2 (small) specific parameters
n_layer: 12
n_head: 12
n_embd: 768
embd_pdrop: 0.1
resid_pdrop: 0.1
attn_pdrop: 0.1
