defaults:
  - model: gpt2_small
  - data: mnist

# --- General --- #
seed: 42
lr: 1e-4

# --- Trainer --- #
trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 10
  accelerator: "auto"
  devices: 1
  logger:
    _target_: pytorch_lightning.loggers.WandbLogger
    project: "next-token-prediction-vision"
    name: "${data.name}-${model.name}"

# --- Checkpointing --- #
checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: "checkpoints/${data.name}/${model.name}"
  filename: "{epoch:02d}-{val_loss:.2f}"
  save_top_k: 1
  monitor: "val_loss"
  mode: "min"
